version: '3.8'
services:
  app:
    image: organization-api
    container_name: organization-api
    build: .
    ports:
      - '8080:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/organization-db
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=M7shey7Secret&%$$*%$
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  redis:
    image: redis
    ports:
      - '6379:6379'
